[package]
name = "Movemate"
version = "1.0.0"
authors = ["David Lucid <david@pentagon.xyz>"]

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
movemate = "0xb2207be128ba3dd1de79c064495a7c97642a513d33d4313e686c33896a332f1a"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/move-stdlib"
rev = "3910637893b6aed4af73b19a2c429ef717e1ee26"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib"
rev = "3910637893b6aed4af73b19a2c429ef717e1ee26"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "3910637893b6aed4af73b19a2c429ef717e1ee26"
