[package]
name = "Movemate"
version = "1.0.0"
authors = ["David Lucid <david@pentagon.xyz>"]

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
movemate = "0x3953993C1D8DFB8BAC2DA2F4DBA6521BA3E705299760FBEE6695E38BCE712A82"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/move-stdlib"
rev = "aptos-framework-v0.3.0"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib"
rev = "aptos-framework-v0.3.0"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "aptos-framework-v0.3.0"
