[package]
name = "Movemate"
version = "1.3.0"
authors = ["David Lucid <david@pentagon.xyz>"]

[addresses]
std = "0x1"
sui = "0x2"
movemate = "0x0"

[dependencies.MoveStdlib]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/deps/move-stdlib"
# devnet-0.15.1
rev = "55962d2fd8ae22241c11de3db39dd2f00fc7319a"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
# devnet-0.15.1
rev = "55962d2fd8ae22241c11de3db39dd2f00fc7319a"
